/**
 * Created by PawełG on 2015-12-28.
 */
$(document).ready(function(){
    $("#titleRow").css('height',$(window).height()/5+'px');
    $("#leagueRow").css('height', $(window).height()/5+'px');
    $("#countRow").css('height',$(window).height()/5+'px');
    $(".form-group").css('margin-top',$(window).height()/10-33+'px');
    $("#orbRow").css('height',$(window).height()/5+'px');
    $("#subOrbRow").css('margin-top',$(window).height()/10-38+'px');
    $("#buttonRow").css('height',$(window).height()/5+'px');
    $("#checkres").css('margin-top',$(window).height()/10-18+'px');
    $(window).resize(function(){
        $("#titleRow").css('height',$(window).height()/5+'px');
        $("#leagueRow").css('height', $(window).height()/5+'px');
        $("#countRow").css('height',$(window).height()/5+'px');
        $(".form-group").css('margin-top',$(window).height()/10-33+'px');
        $("#orbRow").css('height',$(window).height()/5+'px');
        $("#subOrbRow").css('margin-top',$(window).height()/10-38+'px');
        $("#buttonRow").css('height',$(window).height()/5+'px');
        $("#checkres").css('margin-top',$(window).height()/10-18+'px');
    });
    var eProgramStates={
        CALC: 0,
        RESL: 1
    };
    var state=eProgramStates.CALC;
    var orbsvalue=[];
    var chosenorb=0;
    $(".fa-angle-left").click(function(){
        if(chosenorb==0){
            chosenorb=14;
        }
        else{
            --chosenorb;
        }
        console.log(chosenorb);
        $("#orbImg").attr('src','images/orb'+chosenorb+'.png');
        if(state==eProgramStates.RESL){
            $("#count").val(orbsvalue[chosenorb].toFixed(2));
        }
    });
    $(".fa-angle-right").click(function(){
        if(chosenorb==14){
            chosenorb=0;
        }
        else{
            ++chosenorb;
        }
        console.log(chosenorb);
        $("#orbImg").attr('src','images/orb'+chosenorb+'.png');
        if(state==eProgramStates.RESL){
            $("#count").val(orbsvalue[chosenorb].toFixed(2));
        }
    });
    $("#checkres").click(function(){
        if(state==eProgramStates.CALC){
            if($.isNumeric($("#count").val())){
                switch ($("#leagueSelect").val()){
                    case 'Standard':
                        switch(chosenorb){
                            case 0:
                                orbsvalue[0]=$("#count").val();
                                orbsvalue[1]=$("#count").val()*(4/5);
                                orbsvalue[2]=$("#count").val()*(2/5);
                                orbsvalue[3]=$("#count").val()*(2/5);
                                orbsvalue[4]=$("#count").val()*(1/6);
                                orbsvalue[5]=$("#count").val()*(1/9);
                                orbsvalue[6]=$("#count").val()*(1/10);
                                orbsvalue[7]=$("#count").val()*(1/10);
                                orbsvalue[8]=$("#count").val()*(1/15);
                                orbsvalue[9]=$("#count").val()*(1/12);
                                orbsvalue[10]=$("#count").val()*(1/19);
                                orbsvalue[11]=$("#count").val()*(1/28);
                                orbsvalue[12]=$("#count").val()*(1/55);
                                orbsvalue[13]=$("#count").val()*(1/141);
                                orbsvalue[14]=$("#count").val()*(1/218);
                                break;
                            case 1:
                                orbsvalue[0]=$("#count").val()*(5/4);
                                orbsvalue[1]=$("#count").val();
                                orbsvalue[2]=$("#count").val()*(1/2);
                                orbsvalue[3]=$("#count").val()*(1/2);
                                orbsvalue[4]=$("#count").val()*(1/5);
                                orbsvalue[5]=$("#count").val()*(1/8);
                                orbsvalue[6]=$("#count").val()*(1/8);
                                orbsvalue[7]=$("#count").val()*(1/8);
                                orbsvalue[8]=$("#count").val()*(1/12);
                                orbsvalue[9]=$("#count").val()*(1/11);
                                orbsvalue[10]=$("#count").val()*(1/16);
                                orbsvalue[11]=$("#count").val()*(1/24);
                                orbsvalue[12]=$("#count").val()*(1/52);
                                orbsvalue[13]=$("#count").val()*(1/119);
                                orbsvalue[14]=$("#count").val()*(1/309);
                                break;
                            case 2:
                                orbsvalue[0]=$("#count").val()*(5/2);
                                orbsvalue[1]=$("#count").val()*2;
                                orbsvalue[2]=$("#count").val();
                                orbsvalue[3]=$("#count").val();
                                orbsvalue[4]=$("#count").val()*(2/5);
                                orbsvalue[5]=$("#count").val()*(1/4);
                                orbsvalue[6]=$("#count").val()*(1/4);
                                orbsvalue[7]=$("#count").val()*(1/4);
                                orbsvalue[8]=$("#count").val()*(1/6);
                                orbsvalue[9]=$("#count").val()*(1/7);
                                orbsvalue[10]=$("#count").val()*(1/8);
                                orbsvalue[11]=$("#count").val()*(1/12);
                                orbsvalue[12]=$("#count").val()*(1/25);
                                orbsvalue[13]=$("#count").val()*(1/61);
                                orbsvalue[14]=$("#count").val()*(1/142);
                                break;
                            case 3:
                                orbsvalue[0]=$("#count").val()*(5/2);
                                orbsvalue[1]=$("#count").val()*2;
                                orbsvalue[2]=$("#count").val();
                                orbsvalue[3]=$("#count").val();
                                orbsvalue[4]=$("#count").val()*(2/5);
                                orbsvalue[5]=$("#count").val()*(1/4);
                                orbsvalue[6]=$("#count").val()*(1/4);
                                orbsvalue[7]=$("#count").val()*(1/4);
                                orbsvalue[8]=$("#count").val()*(1/6);
                                orbsvalue[9]=$("#count").val()*(1/7);
                                orbsvalue[10]=$("#count").val()*(1/8);
                                orbsvalue[11]=$("#count").val()*(1/12);
                                orbsvalue[12]=$("#count").val()*(1/25);
                                orbsvalue[13]=$("#count").val()*(1/61);
                                orbsvalue[14]=$("#count").val()*(1/142);
                                break;
                            case 4:
                                orbsvalue[0]=$("#count").val()*6;
                                orbsvalue[1]=$("#count").val()*5;
                                orbsvalue[2]=$("#count").val()*(5/2);
                                orbsvalue[3]=$("#count").val()*(5/2);
                                orbsvalue[4]=$("#count").val();
                                orbsvalue[5]=$("#count").val()*(5/7);
                                orbsvalue[6]=$("#count").val()*(5/7);
                                orbsvalue[7]=$("#count").val()*(5/7);
                                orbsvalue[8]=$("#count").val()*(5/12);
                                orbsvalue[9]=$("#count").val()*(1/3);
                                orbsvalue[10]=$("#count").val()*(5/16);
                                orbsvalue[11]=$("#count").val()*(5/24);
                                orbsvalue[12]=$("#count").val()*(5/42);
                                orbsvalue[13]=$("#count").val()*(1/24);
                                orbsvalue[14]=$("#count").val()*(1/45);
                                break;
                            case 5:
                                orbsvalue[0]=$("#count").val()*9;
                                orbsvalue[1]=$("#count").val()*8;
                                orbsvalue[2]=$("#count").val()*4;
                                orbsvalue[3]=$("#count").val()*4;
                                orbsvalue[4]=$("#count").val()*(7/5);
                                orbsvalue[5]=$("#count").val();
                                orbsvalue[6]=$("#count").val();
                                orbsvalue[7]=$("#count").val();
                                orbsvalue[8]=$("#count").val()*(2/3);
                                orbsvalue[9]=$("#count").val()*(1/2);
                                orbsvalue[10]=$("#count").val()*(1/2);
                                orbsvalue[11]=$("#count").val()*(1/3);
                                orbsvalue[12]=$("#count").val()*(1/7);
                                orbsvalue[13]=$("#count").val()*(1/16);
                                orbsvalue[14]=$("#count").val()*(1/47);
                                break;
                            case 6:
                                orbsvalue[0]=$("#count").val()*10;
                                orbsvalue[1]=$("#count").val()*8;
                                orbsvalue[2]=$("#count").val()*4;
                                orbsvalue[3]=$("#count").val()*4;
                                orbsvalue[4]=$("#count").val()*(7/5);
                                orbsvalue[5]=$("#count").val();
                                orbsvalue[6]=$("#count").val();
                                orbsvalue[7]=$("#count").val();
                                orbsvalue[8]=$("#count").val()*(2/3);
                                orbsvalue[9]=$("#count").val()*(1/3);
                                orbsvalue[10]=$("#count").val()*(1/2);
                                orbsvalue[11]=$("#count").val()*(1/3);
                                orbsvalue[12]=$("#count").val()*(1/7);
                                orbsvalue[13]=$("#count").val()*(1/15);
                                orbsvalue[14]=$("#count").val()*(1/46);
                                break;
                            case 7:
                                orbsvalue[0]=$("#count").val()*10;
                                orbsvalue[1]=$("#count").val()*8;
                                orbsvalue[2]=$("#count").val()*4;
                                orbsvalue[3]=$("#count").val()*4;
                                orbsvalue[4]=$("#count").val()*(8/5);
                                orbsvalue[5]=$("#count").val();
                                orbsvalue[6]=$("#count").val();
                                orbsvalue[7]=$("#count").val();
                                orbsvalue[8]=$("#count").val()*(2/3);
                                orbsvalue[9]=$("#count").val()*(1/2);
                                orbsvalue[10]=$("#count").val()*(1/2);
                                orbsvalue[11]=$("#count").val()*(1/3);
                                orbsvalue[12]=$("#count").val()*(1/6);
                                orbsvalue[13]=$("#count").val()*(1/15);
                                orbsvalue[14]=$("#count").val()*(1/36);
                                break;
                            case 8:
                                orbsvalue[0]=$("#count").val()*15;
                                orbsvalue[1]=$("#count").val()*12;
                                orbsvalue[2]=$("#count").val()*6;
                                orbsvalue[3]=$("#count").val()*6;
                                orbsvalue[4]=$("#count").val()*(12/5);
                                orbsvalue[5]=$("#count").val()*(3/2);
                                orbsvalue[6]=$("#count").val()*(3/2);
                                orbsvalue[7]=$("#count").val()*(3/2);
                                orbsvalue[8]=$("#count").val();
                                orbsvalue[9]=$("#count").val()*(3/4);
                                orbsvalue[10]=$("#count").val()*(3/4);
                                orbsvalue[11]=$("#count").val()*(1/2);
                                orbsvalue[12]=$("#count").val()*(1/4);
                                orbsvalue[13]=$("#count").val()*(1/10);
                                orbsvalue[14]=$("#count").val()*(1/26);
                                break;
                            case 9:
                                orbsvalue[0]=$("#count").val()*12;
                                orbsvalue[1]=$("#count").val()*11;
                                orbsvalue[2]=$("#count").val()*7;
                                orbsvalue[3]=$("#count").val()*7;
                                orbsvalue[4]=$("#count").val()*3;
                                orbsvalue[5]=$("#count").val()*2;
                                orbsvalue[6]=$("#count").val()*3;
                                orbsvalue[7]=$("#count").val()*2;
                                orbsvalue[8]=$("#count").val()*(4/3);
                                orbsvalue[9]=$("#count").val();
                                orbsvalue[10]=$("#count").val()*(1/2);
                                orbsvalue[11]=$("#count").val()*(1/2);
                                orbsvalue[12]=$("#count").val()*(1/3);
                                orbsvalue[13]=$("#count").val()*(2/19);
                                orbsvalue[14]=$("#count").val()*(1/45);
                                break;
                            case 10:
                                orbsvalue[0]=$("#count").val()*19;
                                orbsvalue[1]=$("#count").val()*16;
                                orbsvalue[2]=$("#count").val()*8;
                                orbsvalue[3]=$("#count").val()*8;
                                orbsvalue[4]=$("#count").val()*(16/5);
                                orbsvalue[5]=$("#count").val()*2;
                                orbsvalue[6]=$("#count").val()*2;
                                orbsvalue[7]=$("#count").val()*2;
                                orbsvalue[8]=$("#count").val()*(4/3);
                                orbsvalue[9]=$("#count").val()*2;
                                orbsvalue[10]=$("#count").val();
                                orbsvalue[11]=$("#count").val()*(2/3);
                                orbsvalue[12]=$("#count").val()*(1/3);
                                orbsvalue[13]=$("#count").val()*(2/15);
                                orbsvalue[14]=$("#count").val()*(1/15);
                                break;
                            case 11:
                                orbsvalue[0]=$("#count").val()*28;
                                orbsvalue[1]=$("#count").val()*24;
                                orbsvalue[2]=$("#count").val()*12;
                                orbsvalue[3]=$("#count").val()*12;
                                orbsvalue[4]=$("#count").val()*(24/5);
                                orbsvalue[5]=$("#count").val()*3;
                                orbsvalue[6]=$("#count").val()*3;
                                orbsvalue[7]=$("#count").val()*3;
                                orbsvalue[8]=$("#count").val()*2;
                                orbsvalue[9]=$("#count").val()*2;
                                orbsvalue[10]=$("#count").val()*(3/2);
                                orbsvalue[11]=$("#count").val();
                                orbsvalue[12]=$("#count").val()*(1/2);
                                orbsvalue[13]=$("#count").val()*(1/5);
                                orbsvalue[14]=$("#count").val()*(1/11);
                                break;
                            case 12:
                                orbsvalue[0]=$("#count").val()*55;
                                orbsvalue[1]=$("#count").val()*52;
                                orbsvalue[2]=$("#count").val()*25;
                                orbsvalue[3]=$("#count").val()*23;
                                orbsvalue[4]=$("#count").val()*(42/5);
                                orbsvalue[5]=$("#count").val()*7;
                                orbsvalue[6]=$("#count").val()*7;
                                orbsvalue[7]=$("#count").val()*6;
                                orbsvalue[8]=$("#count").val()*4;
                                orbsvalue[9]=$("#count").val()*3;
                                orbsvalue[10]=$("#count").val()*3;
                                orbsvalue[11]=$("#count").val()*2;
                                orbsvalue[12]=$("#count").val();
                                orbsvalue[13]=$("#count").val()*(2/5);
                                orbsvalue[14]=$("#count").val()*(1/9);
                                break;
                            case 13:
                                orbsvalue[0]=$("#count").val()*141;
                                orbsvalue[1]=$("#count").val()*119;
                                orbsvalue[2]=$("#count").val()*61;
                                orbsvalue[3]=$("#count").val()*60;
                                orbsvalue[4]=$("#count").val()*24;
                                orbsvalue[5]=$("#count").val()*16;
                                orbsvalue[6]=$("#count").val()*15;
                                orbsvalue[7]=$("#count").val()*15;
                                orbsvalue[8]=$("#count").val()*10;
                                orbsvalue[9]=$("#count").val()*(19/2);
                                orbsvalue[10]=$("#count").val()*(15/2);
                                orbsvalue[11]=$("#count").val()*5;
                                orbsvalue[12]=$("#count").val()*(5/2);
                                orbsvalue[13]=$("#count").val();
                                orbsvalue[14]=$("#count").val()*(1/2);
                                break;
                            case 14:
                                orbsvalue[0]=$("#count").val()*218;
                                orbsvalue[1]=$("#count").val()*309;
                                orbsvalue[2]=$("#count").val()*142;
                                orbsvalue[3]=$("#count").val()*110;
                                orbsvalue[4]=$("#count").val()*45;
                                orbsvalue[5]=$("#count").val()*47;
                                orbsvalue[6]=$("#count").val()*46;
                                orbsvalue[7]=$("#count").val()*36;
                                orbsvalue[8]=$("#count").val()*26;
                                orbsvalue[9]=$("#count").val()*45;
                                orbsvalue[10]=$("#count").val()*15;
                                orbsvalue[11]=$("#count").val()*11;
                                orbsvalue[12]=$("#count").val()*9;
                                orbsvalue[13]=$("#count").val()*2;
                                orbsvalue[14]=$("#count").val();
                                break;
                    }
                    break;
                    case 'Hardcore':
                        switch(chosenorb){
                            case 0:
                                orbsvalue[0]=$("#count").val();
                                orbsvalue[1]=$("#count").val()*(4/5);
                                orbsvalue[2]=$("#count").val()*(2/5);
                                orbsvalue[3]=$("#count").val()*(2/5);
                                orbsvalue[4]=$("#count").val()*(1/6);
                                orbsvalue[5]=$("#count").val()*(1/9);
                                orbsvalue[6]=$("#count").val()*(1/10);
                                orbsvalue[7]=$("#count").val()*(1/10);
                                orbsvalue[8]=$("#count").val()*(1/15);
                                orbsvalue[9]=$("#count").val()*(1/12);
                                orbsvalue[10]=$("#count").val()*(1/19);
                                orbsvalue[11]=$("#count").val()*(1/28);
                                orbsvalue[12]=$("#count").val()*(1/55);
                                orbsvalue[13]=$("#count").val()*(1/141);
                                orbsvalue[14]=$("#count").val()*(1/218);
                                break;
                            case 1:
                                orbsvalue[0]=$("#count").val()*(5/4);
                                orbsvalue[1]=$("#count").val();
                                orbsvalue[2]=$("#count").val()*(1/2);
                                orbsvalue[3]=$("#count").val()*(1/2);
                                orbsvalue[4]=$("#count").val()*(1/5);
                                orbsvalue[5]=$("#count").val()*(1/8);
                                orbsvalue[6]=$("#count").val()*(1/8);
                                orbsvalue[7]=$("#count").val()*(1/8);
                                orbsvalue[8]=$("#count").val()*(1/12);
                                orbsvalue[9]=$("#count").val()*(1/11);
                                orbsvalue[10]=$("#count").val()*(1/16);
                                orbsvalue[11]=$("#count").val()*(1/24);
                                orbsvalue[12]=$("#count").val()*(1/52);
                                orbsvalue[13]=$("#count").val()*(1/119);
                                orbsvalue[14]=$("#count").val()*(1/309);
                                break;
                            case 2:
                                orbsvalue[0]=$("#count").val()*(5/2);
                                orbsvalue[1]=$("#count").val()*2;
                                orbsvalue[2]=$("#count").val();
                                orbsvalue[3]=$("#count").val();
                                orbsvalue[4]=$("#count").val()*(2/5);
                                orbsvalue[5]=$("#count").val()*(1/4);
                                orbsvalue[6]=$("#count").val()*(1/4);
                                orbsvalue[7]=$("#count").val()*(1/4);
                                orbsvalue[8]=$("#count").val()*(1/6);
                                orbsvalue[9]=$("#count").val()*(1/7);
                                orbsvalue[10]=$("#count").val()*(1/8);
                                orbsvalue[11]=$("#count").val()*(1/12);
                                orbsvalue[12]=$("#count").val()*(1/25);
                                orbsvalue[13]=$("#count").val()*(1/61);
                                orbsvalue[14]=$("#count").val()*(1/142);
                                break;
                            case 3:
                                orbsvalue[0]=$("#count").val()*(5/2);
                                orbsvalue[1]=$("#count").val()*2;
                                orbsvalue[2]=$("#count").val();
                                orbsvalue[3]=$("#count").val();
                                orbsvalue[4]=$("#count").val()*(2/5);
                                orbsvalue[5]=$("#count").val()*(1/4);
                                orbsvalue[6]=$("#count").val()*(1/4);
                                orbsvalue[7]=$("#count").val()*(1/4);
                                orbsvalue[8]=$("#count").val()*(1/6);
                                orbsvalue[9]=$("#count").val()*(1/7);
                                orbsvalue[10]=$("#count").val()*(1/8);
                                orbsvalue[11]=$("#count").val()*(1/12);
                                orbsvalue[12]=$("#count").val()*(1/25);
                                orbsvalue[13]=$("#count").val()*(1/61);
                                orbsvalue[14]=$("#count").val()*(1/142);
                                break;
                            case 4:
                                orbsvalue[0]=$("#count").val()*6;
                                orbsvalue[1]=$("#count").val()*5;
                                orbsvalue[2]=$("#count").val()*(5/2);
                                orbsvalue[3]=$("#count").val()*(5/2);
                                orbsvalue[4]=$("#count").val();
                                orbsvalue[5]=$("#count").val()*(5/7);
                                orbsvalue[6]=$("#count").val()*(5/7);
                                orbsvalue[7]=$("#count").val()*(5/7);
                                orbsvalue[8]=$("#count").val()*(5/12);
                                orbsvalue[9]=$("#count").val()*(1/3);
                                orbsvalue[10]=$("#count").val()*(5/16);
                                orbsvalue[11]=$("#count").val()*(5/24);
                                orbsvalue[12]=$("#count").val()*(5/42);
                                orbsvalue[13]=$("#count").val()*(1/24);
                                orbsvalue[14]=$("#count").val()*(1/45);
                                break;
                            case 5:
                                orbsvalue[0]=$("#count").val()*9;
                                orbsvalue[1]=$("#count").val()*8;
                                orbsvalue[2]=$("#count").val()*4;
                                orbsvalue[3]=$("#count").val()*4;
                                orbsvalue[4]=$("#count").val()*(7/5);
                                orbsvalue[5]=$("#count").val();
                                orbsvalue[6]=$("#count").val();
                                orbsvalue[7]=$("#count").val();
                                orbsvalue[8]=$("#count").val()*(2/3);
                                orbsvalue[9]=$("#count").val()*(1/2);
                                orbsvalue[10]=$("#count").val()*(1/2);
                                orbsvalue[11]=$("#count").val()*(1/3);
                                orbsvalue[12]=$("#count").val()*(1/7);
                                orbsvalue[13]=$("#count").val()*(1/16);
                                orbsvalue[14]=$("#count").val()*(1/47);
                                break;
                            case 6:
                                orbsvalue[0]=$("#count").val()*10;
                                orbsvalue[1]=$("#count").val()*8;
                                orbsvalue[2]=$("#count").val()*4;
                                orbsvalue[3]=$("#count").val()*4;
                                orbsvalue[4]=$("#count").val()*(7/5);
                                orbsvalue[5]=$("#count").val();
                                orbsvalue[6]=$("#count").val();
                                orbsvalue[7]=$("#count").val();
                                orbsvalue[8]=$("#count").val()*(2/3);
                                orbsvalue[9]=$("#count").val()*(1/3);
                                orbsvalue[10]=$("#count").val()*(1/2);
                                orbsvalue[11]=$("#count").val()*(1/3);
                                orbsvalue[12]=$("#count").val()*(1/7);
                                orbsvalue[13]=$("#count").val()*(1/15);
                                orbsvalue[14]=$("#count").val()*(1/46);
                                break;
                            case 7:
                                orbsvalue[0]=$("#count").val()*10;
                                orbsvalue[1]=$("#count").val()*8;
                                orbsvalue[2]=$("#count").val()*4;
                                orbsvalue[3]=$("#count").val()*4;
                                orbsvalue[4]=$("#count").val()*(8/5);
                                orbsvalue[5]=$("#count").val();
                                orbsvalue[6]=$("#count").val();
                                orbsvalue[7]=$("#count").val();
                                orbsvalue[8]=$("#count").val()*(2/3);
                                orbsvalue[9]=$("#count").val()*(1/2);
                                orbsvalue[10]=$("#count").val()*(1/2);
                                orbsvalue[11]=$("#count").val()*(1/3);
                                orbsvalue[12]=$("#count").val()*(1/6);
                                orbsvalue[13]=$("#count").val()*(1/15);
                                orbsvalue[14]=$("#count").val()*(1/36);
                                break;
                            case 8:
                                orbsvalue[0]=$("#count").val()*15;
                                orbsvalue[1]=$("#count").val()*12;
                                orbsvalue[2]=$("#count").val()*6;
                                orbsvalue[3]=$("#count").val()*6;
                                orbsvalue[4]=$("#count").val()*(12/5);
                                orbsvalue[5]=$("#count").val()*(3/2);
                                orbsvalue[6]=$("#count").val()*(3/2);
                                orbsvalue[7]=$("#count").val()*(3/2);
                                orbsvalue[8]=$("#count").val();
                                orbsvalue[9]=$("#count").val()*(3/4);
                                orbsvalue[10]=$("#count").val()*(3/4);
                                orbsvalue[11]=$("#count").val()*(1/2);
                                orbsvalue[12]=$("#count").val()*(1/4);
                                orbsvalue[13]=$("#count").val()*(1/10);
                                orbsvalue[14]=$("#count").val()*(1/26);
                                break;
                            case 9:
                                orbsvalue[0]=$("#count").val()*12;
                                orbsvalue[1]=$("#count").val()*11;
                                orbsvalue[2]=$("#count").val()*7;
                                orbsvalue[3]=$("#count").val()*7;
                                orbsvalue[4]=$("#count").val()*3;
                                orbsvalue[5]=$("#count").val()*2;
                                orbsvalue[6]=$("#count").val()*3;
                                orbsvalue[7]=$("#count").val()*2;
                                orbsvalue[8]=$("#count").val()*(4/3);
                                orbsvalue[9]=$("#count").val();
                                orbsvalue[10]=$("#count").val()*(1/2);
                                orbsvalue[11]=$("#count").val()*(1/2);
                                orbsvalue[12]=$("#count").val()*(1/3);
                                orbsvalue[13]=$("#count").val()*(2/19);
                                orbsvalue[14]=$("#count").val()*(1/45);
                                break;
                            case 10:
                                orbsvalue[0]=$("#count").val()*19;
                                orbsvalue[1]=$("#count").val()*16;
                                orbsvalue[2]=$("#count").val()*8;
                                orbsvalue[3]=$("#count").val()*8;
                                orbsvalue[4]=$("#count").val()*(16/5);
                                orbsvalue[5]=$("#count").val()*2;
                                orbsvalue[6]=$("#count").val()*2;
                                orbsvalue[7]=$("#count").val()*2;
                                orbsvalue[8]=$("#count").val()*(4/3);
                                orbsvalue[9]=$("#count").val()*2;
                                orbsvalue[10]=$("#count").val();
                                orbsvalue[11]=$("#count").val()*(2/3);
                                orbsvalue[12]=$("#count").val()*(1/3);
                                orbsvalue[13]=$("#count").val()*(2/15);
                                orbsvalue[14]=$("#count").val()*(1/15);
                                break;
                            case 11:
                                orbsvalue[0]=$("#count").val()*28;
                                orbsvalue[1]=$("#count").val()*24;
                                orbsvalue[2]=$("#count").val()*12;
                                orbsvalue[3]=$("#count").val()*12;
                                orbsvalue[4]=$("#count").val()*(24/5);
                                orbsvalue[5]=$("#count").val()*3;
                                orbsvalue[6]=$("#count").val()*3;
                                orbsvalue[7]=$("#count").val()*3;
                                orbsvalue[8]=$("#count").val()*2;
                                orbsvalue[9]=$("#count").val()*2;
                                orbsvalue[10]=$("#count").val()*(3/2);
                                orbsvalue[11]=$("#count").val();
                                orbsvalue[12]=$("#count").val()*(1/2);
                                orbsvalue[13]=$("#count").val()*(1/5);
                                orbsvalue[14]=$("#count").val()*(1/11);
                                break;
                            case 12:
                                orbsvalue[0]=$("#count").val()*55;
                                orbsvalue[1]=$("#count").val()*52;
                                orbsvalue[2]=$("#count").val()*25;
                                orbsvalue[3]=$("#count").val()*23;
                                orbsvalue[4]=$("#count").val()*(42/5);
                                orbsvalue[5]=$("#count").val()*7;
                                orbsvalue[6]=$("#count").val()*7;
                                orbsvalue[7]=$("#count").val()*6;
                                orbsvalue[8]=$("#count").val()*4;
                                orbsvalue[9]=$("#count").val()*3;
                                orbsvalue[10]=$("#count").val()*3;
                                orbsvalue[11]=$("#count").val()*2;
                                orbsvalue[12]=$("#count").val();
                                orbsvalue[13]=$("#count").val()*(2/5);
                                orbsvalue[14]=$("#count").val()*(1/9);
                                break;
                            case 13:
                                orbsvalue[0]=$("#count").val()*141;
                                orbsvalue[1]=$("#count").val()*119;
                                orbsvalue[2]=$("#count").val()*61;
                                orbsvalue[3]=$("#count").val()*60;
                                orbsvalue[4]=$("#count").val()*24;
                                orbsvalue[5]=$("#count").val()*16;
                                orbsvalue[6]=$("#count").val()*15;
                                orbsvalue[7]=$("#count").val()*15;
                                orbsvalue[8]=$("#count").val()*10;
                                orbsvalue[9]=$("#count").val()*(19/2);
                                orbsvalue[10]=$("#count").val()*(15/2);
                                orbsvalue[11]=$("#count").val()*5;
                                orbsvalue[12]=$("#count").val()*(5/2);
                                orbsvalue[13]=$("#count").val();
                                orbsvalue[14]=$("#count").val()*(1/2);
                                break;
                            case 14:
                                orbsvalue[0]=$("#count").val()*218;
                                orbsvalue[1]=$("#count").val()*309;
                                orbsvalue[2]=$("#count").val()*142;
                                orbsvalue[3]=$("#count").val()*110;
                                orbsvalue[4]=$("#count").val()*45;
                                orbsvalue[5]=$("#count").val()*47;
                                orbsvalue[6]=$("#count").val()*46;
                                orbsvalue[7]=$("#count").val()*36;
                                orbsvalue[8]=$("#count").val()*26;
                                orbsvalue[9]=$("#count").val()*45;
                                orbsvalue[10]=$("#count").val()*15;
                                orbsvalue[11]=$("#count").val()*11;
                                orbsvalue[12]=$("#count").val()*9;
                                orbsvalue[13]=$("#count").val()*2;
                                orbsvalue[14]=$("#count").val();
                                break;
                        }
                        break;
                }
                $("#title").text("Twoje orby są warte");
                $(this).text("Przelicz ponownie");
                state=eProgramStates.RESL;
            }
            else{
                alert("Wpisz liczbę w prawidłowym formacie")
            }
        }
        else{
            $("#title").text("Ile warte są twoje orby");
            $(this).text("Sprawdź cenę");
            state=eProgramStates.CALC;
        }
    });
});